# Spring properties
spring:

  # Removes the white label error page
  web:
    resources:
      add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true

  # Flyway
  flyway:
    locations: "classpath:migrations/{vendor}"
