spring:

  # Datasource
  datasource:
    url: jdbc:postgresql://auth-db:5432/authdb
    driverClassName: org.postgresql.Driver
    username: authdb
    password: password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  # Flyway
  flyway:
    enabled: false

# App properties
banking-api:
  allowed-origins: "http://localhost:4200"
