# Use root/example as user/password credentials
version: '3.1'

services:

  # Api
  api:
    build: ./sample-banking-api/
    ports:
      - 9090:8080
    environment:
      # Spring profile
      SPRING_PROFILES_ACTIVE: prod

  # Auth
  auth:
    build: ./sample-auth-api/
    ports:
      - 9091:8080
    environment:
      # Spring profile
      SPRING_PROFILES_ACTIVE: prod

  # Api Database
  api-db:
    image: postgres
    restart: always
    volumes:
      - ./database/api-db/init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: apidb
      POSTGRES_PASSWORD: password

  # Auth Database
  auth-db:
    image: postgres
    restart: always
    volumes:
      - ./database/auth-db/init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: authdb
      POSTGRES_PASSWORD: password
