# Spring properties
spring:

  # Removes the white label error page
  web:
    resources:
      add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true

  # Liquibase
  liquibase:
    change-log: "classpath:migrations/db.changelog-master.xml"
  sql:
    init:
      platform: "h2"
      data-locations: "optional:classpath*:data/h2/db.data-*.sql"

# App properties
banking-api:
  iban-api-url: https://openiban.com/
  allowed-origins: http://localhost:4200
