spring:

  # Datasource
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

# App properties
banking-api:
  allowed-origins: "http://localhost:4200"
  auth: none
