server:
  port: 9090

spring:

  # Datasource
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        globally_quoted_identifiers: true

# App properties
banking-api:
  allowed-origins: "http://localhost:4200"
  auth: none
