spring:

  # Datasource
  datasource:
    url: jdbc:postgresql://api-db:5432/apidb
    driverClassName: org.postgresql.Driver
    username: apidb
    password: password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        globally_quoted_identifiers: true

  # Flyway
  flyway:
    enabled: false


# App properties
banking-api:
  allowed-origins: "http://localhost:4200"
