# Spring properties
spring:

  # Removes the white label error page
  web:
    resources:
      add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true

  # Flyway
  flyway:
    locations: "classpath:migrations/{vendor}"

# App properties
banking-api:
  iban-api-url: https://openiban.com/
  allowed-origins: http://localhost:4200
